### ISSUE TITLE
Problem when submitting a form via AJAX

### ISSUE THREAD

**Issue by jlewis-ebi** [vote539/placeholdr#3]
There is an issue when a form is submitted via AJAX.  After the call completes if you rerun the placeholdr function the placeholders do not display because the input fields have already been polyfilled.  If you update the code as below, everything works great.

// leave now if we've polyfilled this element before
//if ($this.data(ns)) return;
if ($this.data(ns)) {
    if ($this.val() === "") putPlaceholder.call(this);
    return;
}

**Comment by vote539** [comment]
This is a good catch.  I just submitted something that should fix it.  Whenever `.val("")` is called with an empty value, Placeholdr should put the placeholder back again, but it was not doing this.  Now it is.
