### ISSUE TITLE
Override native IE10+ placeholder behavior, disappearing text on focus

### ISSUE THREAD

**Issue by danielHalan** [vote539/placeholdr#5]
modern IE native placeholder feature clears the text on Focus, which isnt so good when using JS to pre-select a textbox.

Is there a way to override this behavior? if not, would be a nice feature

**Comment by LeonardoGentile** [comment]
:+1:

**Comment by vote539** [comment]
This script had one purpose only, which was to provide polyfills for old browsers.  It's out-of-scope for it to provide additional features.  If you code up your own solution I'll gladly add a link to it from the README.
